---
# tasks file for ntp
- name: Make sure chrony package is installed
  package:
    name: chrony
    state: present

- name: 'Ensure chrony is enabled and running'
  service:
    name: "{{ chrony_svc }}"
    state: started
    enabled: true

- name: ntp configuration
  template:
    src: chrony.j2
    dest: /etc/chrony.conf
    mode: 0644
    owner: root 
  notify: restart_chrony
