- name: Deploying NTP role
  hosts: all
  roles:
    - role: ntp
      vars:
        output: "This will override the role vars and defaults" 
  tasks:
    - name: print the outputs
      debug:
        msg: "{{ output }}"
