- name: Loop in Templates
  hosts: dbserver
  tasks:
    - name: Loop the inventory groups
      template:
        src: /home/opc/working-with-ansible/jinja-templates/loop-2.j2
        dest: /tmp/hosts_with_port.txt
