---
- name: Integerating Ansible with Jira
  hosts: localhost
  vars_files:
    - secrets.yml
  vars: 
    jirauri: "https://mdizhar3103.atlassian.net"
  tasks:
    - name: Create a Jira Issue
      jira: 
        uri: "{{ jirauri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        project: MFP    # enter project key
        operation: create 
        issuetype: Task 
        summary: First Jira Integeration Issue 
        description: Issue created from Ansible
